In [ ]:
import os
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
pip install kashgari==2.0.0

     |████████████████████████████████| 92kB 3.8MB/s 
     |████████████████████████████████| 51kB 4.7MB/s 
     |████████████████████████████████| 24.2MB 1.3MB/s 
     |████████████████████████████████| 378kB 38.7MB/s 
     |████████████████████████████████| 51kB 2.7MB/s 
  Created wheel for bert4keras: filename=bert4keras-0.9.7-cp36-none-any.whl size=43299 sha256=fab2cf86da9aede472ab56763fbf7fd657277a3d71bc0bf9e1ab1c5470f13582
  Stored in directory: /root/.cache/pip/wheels/71/7b/06/4b4bca2005cfccd3a157cb012d1f91a83c252442c9358c238c
Successfully built bert4keras
  Found existing installation: Keras 2.4.3
    Uninstalling Keras-2.4.3:
      Successfully uninstalled Keras-2.4.3
  Found existing installation: gensim 3.6.0
    Uninstalling gensim-3.6.0:
      Successfully uninstalled gensim-3.6.0


In [ ]:
os.chdir("/content/drive/MyDrive/AiCup-1") #更改路徑
os.getcwd() #查看當前路徑

'/content/drive/MyDrive/AiCup-1'

In [ ]:
import numpy as np

file_path='test.txt'

def loadInputFile(path):
    trainingset = list()  # store trainingset [content,content,...]
    with open(file_path, 'r', encoding='utf8') as f:
        file_text=f.read().encode('utf-8').decode('utf-8-sig')
    datas=file_text.split('\n\n--------------------\n\n')[:-1]
    for data in datas:
        data=data.split('\n')
        content=data[1]
        trainingset.append(content)


    
    return trainingset

trainingset= loadInputFile(file_path)





In [ ]:
import kashgari
import re

loaded_model = kashgari.utils.load_model('BiLSTM_CRF_Model_2.h5')

labels = []
def cut_text(text, lenth):
    textArr = re.findall('.{' + str(lenth) + '}', text)
    textArr.append(text[(len(textArr) * lenth):])
    return textArr



def extract_labels(text, ners ,article):
    p=0
    ner_reg_list = []
    if ners:
        new_ners = []
        for ner in ners:
            new_ners += ner;
        for word, tag in zip([char for char in text], new_ners):
            if tag != 'O':
                ner_reg_list.append((word, tag , p))
            p+=1 

    #print(ner_reg_list)
    # 输出模型的NER识别结果
    #labels = {}
    
    if ner_reg_list:
        for i, item in enumerate(ner_reg_list):
            if item[1].startswith('B'):
                label = ""
                end = i + 1
                
                while end <= len(ner_reg_list) - 1 and ner_reg_list[end][1].startswith('I'):
                    end += 1

                ner_type = item[1].split('-')[1]
                label += ''.join([item[0] for item in ner_reg_list[i:end]])
                labels.append([article, item[2], int(item[2])+len(label) ,label, ner_type])

               
                
    return labels

for t in range(len(trainingset)):
    print("article:",t)
    text_input = trainingset[t]

    texts = cut_text(text_input, 100)

    ners = loaded_model.predict([[char for char in text] for text in texts])
    #print(ners)
    labels = extract_labels(text_input, ners , t)
    #print(labels)
    


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: DeprecationWarning: The 'load_model' function is deprecated, use 'XX_Model.load_model' instead
  after removing the cwd from sys.path.
2020-12-28 12:55:32,543 [DEBUG] kashgari - ------------------------------------------------
2020-12-28 12:55:32,544 [DEBUG] kashgari - Loaded transformer model's vocab
2020-12-28 12:55:32,545 [DEBUG] kashgari - config_path       : chinese_L-12_H-768_A-12/bert_config.json
2020-12-28 12:55:32,546 [DEBUG] kashgari - vocab_path      : chinese_L-12_H-768_A-12/vocab.txt
2020-12-28 12:55:32,547 [DEBUG] kashgari - checkpoint_path : chinese_L-12_H-768_A-12/bert_model.ckpt
2020-12-28 12:55:32,548 [DEBUG] kashgari - Top 50 words    : ['[PAD]', '[unused1]', '[unused2]', '[unused3]', '[unused4]', '[unused5]', '[unused6]', '[unused7]', '[unused8]', '[unused9]', '[unused10]', '[unused11]', '[unused12]', '[unused13]', '[unused14]', '[unused15]', '[unused16]', '[unused17]', '[unused18]', '[unused19]', '[unu

{"class_name": "Functional", "config": {"name": "model_17", "layers": [{"class_name": "InputLayer", "config": {"batch_input_shape": [null, null], "dtype": "float32", "sparse": false, "ragged": false, "name": "Input-Token"}, "name": "Input-Token", "inbound_nodes": []}, {"class_name": "InputLayer", "config": {"batch_input_shape": [null, null], "dtype": "float32", "sparse": false, "ragged": false, "name": "Input-Segment"}, "name": "Input-Segment", "inbound_nodes": []}, {"class_name": "Embedding", "config": {"name": "Embedding-Token", "trainable": false, "batch_input_shape": [null, null], "dtype": "float32", "input_dim": 21128, "output_dim": 768, "embeddings_initializer": {"class_name": "TruncatedNormal", "config": {"mean": 0.0, "stddev": 0.02, "seed": null}}, "embeddings_regularizer": null, "activity_regularizer": null, "embeddings_constraint": null, "mask_zero": true, "input_length": null}, "name": "Embedding-Token", "inbound_nodes": [[["Input-Token", 0, 0, {}]]]}, {"class_name": "Embedd

2020-12-28 12:55:53,837 [WARNING] kashgari - Sequence length is None, will use the max length of the samples, which is 102
2020-12-28 12:55:53,839 [DEBUG] kashgari - predict seq_length: None, input: (2, 6, 102)


article: 0
None
1/1 [==============================] - 9s 9s/step


2020-12-28 12:56:02,426 [DEBUG] kashgari - predict output: (6, 102)
2020-12-28 12:56:02,431 [DEBUG] kashgari - predict output argmax: [[0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 3 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 9 6 1 1 1 1 1 1
  1 1 9 6 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 3 2 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 

article: 1
None
1/1 [==============================] - 4s 4s/step


2020-12-28 12:56:06,407 [DEBUG] kashgari - predict output: (11, 102)
2020-12-28 12:56:06,409 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 12:56:06,413 [DEBUG] kashgari - predict seq_length: None, input: (2, 19, 102)


article: 2
None
1/1 [==============================] - 6s 6s/step


2020-12-28 12:56:12,859 [DEBUG] kashgari - predict output: (19, 102)
2020-12-28 12:56:12,860 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 12:56:12,863 [DEBUG] kashgari - predict seq_length: None, input: (2, 10, 102)


article: 3
None
1/1 [==============================] - 3s 3s/step


2020-12-28 12:56:16,350 [DEBUG] kashgari - predict output: (10, 102)
2020-12-28 12:56:16,352 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 12:56:16,355 [DEBUG] kashgari - predict seq_length: None, input: (2, 6, 102)


article: 4
None
1/1 [==============================] - 2s 2s/step


2020-12-28 12:56:18,555 [DEBUG] kashgari - predict output: (6, 102)
2020-12-28 12:56:18,558 [DEBUG] kashgari - predict output argmax: [[0 1 1 1 1 1 1 9 6 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 3 2 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 7 4 4 4 4 1 1 1 1 7 4 4 4 4 1 7 4 4 4 4 1 1 1
  1 1 7 4 4 4 4 4 1 1 1 1 1 1 1 1 3 2 2 2 2 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 7 4 4 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 7 4 1 1 7 1 1 1 1 1 1 7 0]
 [0 1 1 1 7 4 1 1 1 1 1 1 1 1 1 1 1 1 1 1 7 4 1 1 1 1 1 7 4 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 3 2 2 1 3 2
  2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 

article: 5
None
1/1 [==============================] - 8s 8s/step


2020-12-28 12:56:26,570 [DEBUG] kashgari - predict output: (24, 102)
2020-12-28 12:56:26,572 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 4 4 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 12:56:26,579 [DEBUG] kashgari - predict seq_length: None, input: (2, 23, 102)


article: 6
None
1/1 [==============================] - 8s 8s/step


2020-12-28 12:56:34,273 [DEBUG] kashgari - predict output: (23, 102)
2020-12-28 12:56:34,275 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 12:56:34,280 [DEBUG] kashgari - predict seq_length: None, input: (2, 13, 102)


article: 7
None
1/1 [==============================] - 4s 4s/step


2020-12-28 12:56:38,699 [DEBUG] kashgari - predict output: (13, 102)
2020-12-28 12:56:38,702 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 3 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 12:56:38,706 [DEBUG] kashgari - predict seq_length: None, input: (2, 12, 102)


article: 8
None
1/1 [==============================] - 4s 4s/step


2020-12-28 12:56:42,736 [DEBUG] kashgari - predict output: (12, 102)
2020-12-28 12:56:42,738 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 12:56:42,743 [DEBUG] kashgari - predict seq_length: None, input: (2, 32, 102)


article: 9
None
1/1 [==============================] - 15s 15s/step


2020-12-28 12:56:57,644 [DEBUG] kashgari - predict output: (32, 102)
2020-12-28 12:56:57,649 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 12:56:57,654 [DEBUG] kashgari - predict seq_length: None, input: (2, 16, 102)


article: 10
None
1/1 [==============================] - 5s 5s/step


2020-12-28 12:57:03,031 [DEBUG] kashgari - predict output: (16, 102)
2020-12-28 12:57:03,033 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 12:57:03,041 [DEBUG] kashgari - predict seq_length: None, input: (2, 66, 102)


article: 11
None
3/3 [==============================] - 22s 6s/step


2020-12-28 12:57:25,384 [DEBUG] kashgari - predict output: (66, 102)
2020-12-28 12:57:25,386 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 12:57:25,392 [DEBUG] kashgari - predict seq_length: None, input: (2, 4, 102)


article: 12
None
1/1 [==============================] - 1s 1s/step


2020-12-28 12:57:26,902 [DEBUG] kashgari - predict output: (4, 102)
2020-12-28 12:57:26,905 [DEBUG] kashgari - predict output argmax: [[0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 3 2
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 3 2 2 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
2020-12-28 12:57:26,9

article: 13
None
1/1 [==============================] - 4s 4s/step


2020-12-28 12:57:31,430 [DEBUG] kashgari - predict output: (13, 102)
2020-12-28 12:57:31,433 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 12:57:31,438 [DEBUG] kashgari - predict seq_length: None, input: (2, 13, 102)


article: 14
None
1/1 [==============================] - 4s 4s/step


2020-12-28 12:57:35,948 [DEBUG] kashgari - predict output: (13, 102)
2020-12-28 12:57:35,949 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 12:57:35,952 [DEBUG] kashgari - predict seq_length: None, input: (2, 8, 102)


article: 15
None
1/1 [==============================] - 3s 3s/step


2020-12-28 12:57:38,801 [DEBUG] kashgari - predict output: (8, 102)
2020-12-28 12:57:38,804 [DEBUG] kashgari - predict output argmax: [[ 0  1  1  1  1  3  2  2  2  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1 10  5  5  1  1  1  1  1  1 10  5  5  1
   1  1  1  1  1  1  1  1  1  1 10  5  5  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  0]
 [ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  3
   2  2  1  1  1  0]
 [ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  3  2
   2  2  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1

article: 16
None
1/1 [==============================] - 4s 4s/step


2020-12-28 12:57:43,000 [DEBUG] kashgari - predict output: (12, 102)
2020-12-28 12:57:43,002 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 12:57:43,005 [DEBUG] kashgari - predict seq_length: None, input: (2, 8, 102)


article: 17
None
1/1 [==============================] - 3s 3s/step


2020-12-28 12:57:45,825 [DEBUG] kashgari - predict output: (8, 102)
2020-12-28 12:57:45,829 [DEBUG] kashgari - predict output argmax: [[ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  0]
 [ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  0]
 [ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1

article: 18
None
1/1 [==============================] - 6s 6s/step


2020-12-28 12:57:52,377 [DEBUG] kashgari - predict output: (19, 102)
2020-12-28 12:57:52,379 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 12:57:52,384 [DEBUG] kashgari - predict seq_length: None, input: (2, 20, 102)


article: 19
None
1/1 [==============================] - 7s 7s/step


2020-12-28 12:57:59,253 [DEBUG] kashgari - predict output: (20, 102)
2020-12-28 12:57:59,256 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 3 2 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 12:57:59,260 [DEBUG] kashgari - predict seq_length: None, input: (2, 14, 102)


article: 20
None
1/1 [==============================] - 5s 5s/step


2020-12-28 12:58:04,115 [DEBUG] kashgari - predict output: (14, 102)
2020-12-28 12:58:04,117 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 3 2 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 9 6 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 12:58:04,120 [DEBUG] kashgari - predict seq_length: None, input: (2, 10, 102)


article: 21
None
1/1 [==============================] - 3s 3s/step


2020-12-28 12:58:07,647 [DEBUG] kashgari - predict output: (10, 102)
2020-12-28 12:58:07,649 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 7 0]
 [0 1 1 ... 7 4 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 12:58:07,652 [DEBUG] kashgari - predict seq_length: None, input: (2, 8, 102)


article: 22
None
1/1 [==============================] - 3s 3s/step


2020-12-28 12:58:10,529 [DEBUG] kashgari - predict output: (8, 102)
2020-12-28 12:58:10,533 [DEBUG] kashgari - predict output argmax: [[ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  3  2  2  2  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  0]
 [ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  7  4  1  1  1  1  1
   1  7  4  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  0]
 [ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1

article: 23
None
1/1 [==============================] - 7s 7s/step


2020-12-28 12:58:18,029 [DEBUG] kashgari - predict output: (22, 102)
2020-12-28 12:58:18,031 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 12:58:18,035 [DEBUG] kashgari - predict seq_length: None, input: (2, 6, 102)


article: 24
None
1/1 [==============================] - 2s 2s/step


2020-12-28 12:58:20,261 [DEBUG] kashgari - predict output: (6, 102)
2020-12-28 12:58:20,265 [DEBUG] kashgari - predict output argmax: [[0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 3 2 2 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 7 4 1 1 1 1 7 4 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 3 2 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 3 2 2 2 2 1 1 1 1 3 2 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 

article: 25
None
1/1 [==============================] - 3s 3s/step


2020-12-28 12:58:23,131 [DEBUG] kashgari - predict output: (8, 102)
2020-12-28 12:58:23,136 [DEBUG] kashgari - predict output argmax: [[ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  3  2  1  1  1  1  1  1  1  1
   3  2  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  0]
 [ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  3  2  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  3
   2  2  1  1  1  0]
 [ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1

article: 26
None
1/1 [==============================] - 6s 6s/step


2020-12-28 12:58:28,947 [DEBUG] kashgari - predict output: (17, 102)
2020-12-28 12:58:28,949 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 12:58:28,953 [DEBUG] kashgari - predict seq_length: None, input: (2, 13, 102)


article: 27
None
1/1 [==============================] - 5s 5s/step


2020-12-28 12:58:33,510 [DEBUG] kashgari - predict output: (13, 102)
2020-12-28 12:58:33,512 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 12:58:33,517 [DEBUG] kashgari - predict seq_length: None, input: (2, 20, 102)


article: 28
None
1/1 [==============================] - 7s 7s/step


2020-12-28 12:58:40,375 [DEBUG] kashgari - predict output: (20, 102)
2020-12-28 12:58:40,376 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 2 2 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 12:58:40,380 [DEBUG] kashgari - predict seq_length: None, input: (2, 10, 102)


article: 29
None
1/1 [==============================] - 4s 4s/step


2020-12-28 12:58:43,966 [DEBUG] kashgari - predict output: (10, 102)
2020-12-28 12:58:43,969 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 12:58:43,973 [DEBUG] kashgari - predict seq_length: None, input: (2, 13, 102)


article: 30
None
1/1 [==============================] - 5s 5s/step


2020-12-28 12:58:48,589 [DEBUG] kashgari - predict output: (13, 102)
2020-12-28 12:58:48,590 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 3 2 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 12:58:48,595 [DEBUG] kashgari - predict seq_length: None, input: (2, 20, 102)


article: 31
None
1/1 [==============================] - 7s 7s/step


2020-12-28 12:58:55,427 [DEBUG] kashgari - predict output: (20, 102)
2020-12-28 12:58:55,430 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 12:58:55,434 [DEBUG] kashgari - predict seq_length: None, input: (2, 12, 102)


article: 32
None
1/1 [==============================] - 4s 4s/step


2020-12-28 12:58:59,682 [DEBUG] kashgari - predict output: (12, 102)
2020-12-28 12:58:59,684 [DEBUG] kashgari - predict output argmax: [[ 0  1  1 ...  1  1  0]
 [ 0  1  1 ...  1  1  0]
 [ 0  1  1 ...  1  1  0]
 ...
 [ 0  1  1 ...  1  1  0]
 [ 0  1 10 ...  1  1  0]
 [ 0  1  1 ...  1  1  1]]
2020-12-28 12:58:59,690 [DEBUG] kashgari - predict seq_length: None, input: (2, 7, 102)


article: 33
None
1/1 [==============================] - 3s 3s/step


2020-12-28 12:59:02,250 [DEBUG] kashgari - predict output: (7, 102)
2020-12-28 12:59:02,253 [DEBUG] kashgari - predict output argmax: [[0 1 1 1 3 2 2 1 1 1 1 1 1 1 1 1 3 2 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 7 4 4 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 3 2 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 3 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 3 2 2 1 1 1 1 1 1 

article: 34
None
1/1 [==============================] - 3s 3s/step


2020-12-28 12:59:04,821 [DEBUG] kashgari - predict output: (7, 102)
2020-12-28 12:59:04,824 [DEBUG] kashgari - predict output argmax: [[0 1 1 1 3 2 1 3 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 3 2 2 1 1 1 1 1 1 7 4 4 1 3 2 2 2 2 1 1 1 1 1 1 1 1 1 1 1 1 3 2 1
  1 1 1 1 3 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 3 2 1 3 2 1 3 2 1 1 1 1 1 1 1 1 1 3 2 1 3 0]
 [0 1 1 1 1 1 1 1 1 1 

article: 35
None
1/1 [==============================] - 7s 7s/step


2020-12-28 12:59:11,371 [DEBUG] kashgari - predict output: (19, 102)
2020-12-28 12:59:11,373 [DEBUG] kashgari - predict output argmax: [[ 0  1  1 ...  1  1  0]
 [ 0  1  1 ...  1  1  0]
 [ 0  1  1 ...  1  1  0]
 ...
 [ 0  1  3 ...  1  1  0]
 [ 0  1  1 ...  1  1  0]
 [ 0  1 16 ...  1  1  1]]
2020-12-28 12:59:11,378 [DEBUG] kashgari - predict seq_length: None, input: (2, 12, 102)


article: 36
None
1/1 [==============================] - 4s 4s/step


2020-12-28 12:59:15,566 [DEBUG] kashgari - predict output: (12, 102)
2020-12-28 12:59:15,568 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 7 0]
 [0 1 4 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 12:59:15,571 [DEBUG] kashgari - predict seq_length: None, input: (2, 6, 102)


article: 37
None
1/1 [==============================] - 2s 2s/step


2020-12-28 12:59:17,786 [DEBUG] kashgari - predict output: (6, 102)
2020-12-28 12:59:17,791 [DEBUG] kashgari - predict output argmax: [[ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  7  4  4  1  1  1  1  7  4  4  1  1  1
   1  1  1  1  1  0]
 [ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  3  2  2  2  1  1  1  1
   1  1  1  1  1  0]
 [ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1

article: 38
None
1/1 [==============================] - 3s 3s/step


2020-12-28 12:59:20,709 [DEBUG] kashgari - predict output: (8, 102)
2020-12-28 12:59:20,713 [DEBUG] kashgari - predict output argmax: [[ 0  1  1  1  1  1  1  1  1  1  1  1  1  3  2  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  0]
 [ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  0]
 [ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1

article: 39
None
1/1 [==============================] - 6s 6s/step


2020-12-28 12:59:26,295 [DEBUG] kashgari - predict output: (16, 102)
2020-12-28 12:59:26,297 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 12:59:26,300 [DEBUG] kashgari - predict seq_length: None, input: (2, 6, 102)


article: 40
None
1/1 [==============================] - 2s 2s/step


2020-12-28 12:59:28,528 [DEBUG] kashgari - predict output: (6, 102)
2020-12-28 12:59:28,533 [DEBUG] kashgari - predict output argmax: [[0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 3 2 1 1 1 1 1 1 1
  1 3 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 

article: 41
None
1/1 [==============================] - 10s 10s/step


2020-12-28 12:59:38,653 [DEBUG] kashgari - predict output: (29, 102)
2020-12-28 12:59:38,654 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 12:59:38,660 [DEBUG] kashgari - predict seq_length: None, input: (2, 16, 102)


article: 42
None
1/1 [==============================] - 6s 6s/step


2020-12-28 12:59:44,302 [DEBUG] kashgari - predict output: (16, 102)
2020-12-28 12:59:44,304 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 9 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 12:59:44,307 [DEBUG] kashgari - predict seq_length: None, input: (2, 11, 102)


article: 43
None
1/1 [==============================] - 6s 6s/step


2020-12-28 12:59:50,759 [DEBUG] kashgari - predict output: (11, 102)
2020-12-28 12:59:50,764 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 4 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 12:59:50,776 [DEBUG] kashgari - predict seq_length: None, input: (2, 12, 102)


article: 44
None
1/1 [==============================] - 5s 5s/step


2020-12-28 12:59:56,103 [DEBUG] kashgari - predict output: (12, 102)
2020-12-28 12:59:56,106 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 12:59:56,110 [DEBUG] kashgari - predict seq_length: None, input: (2, 33, 102)


article: 45
None
2/2 [==============================] - 11s 466ms/step


2020-12-28 13:00:07,511 [DEBUG] kashgari - predict output: (33, 102)
2020-12-28 13:00:07,514 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:00:07,520 [DEBUG] kashgari - predict seq_length: None, input: (2, 5, 102)


article: 46
None
1/1 [==============================] - 2s 2s/step


2020-12-28 13:00:09,454 [DEBUG] kashgari - predict output: (5, 102)
2020-12-28 13:00:09,457 [DEBUG] kashgari - predict output argmax: [[ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  0]
 [ 0  1  1  1  1  1  1  1  1  1  1 10  5  5  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  0]
 [ 0  3  2  2  2  1  1  1  1  1  1  1  1  1 10  5  5  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  3  2  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1

article: 47
None
1/1 [==============================] - 4s 4s/step


2020-12-28 13:00:13,305 [DEBUG] kashgari - predict output: (11, 102)
2020-12-28 13:00:13,308 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:00:13,313 [DEBUG] kashgari - predict seq_length: None, input: (2, 19, 102)


article: 48
None
1/1 [==============================] - 6s 6s/step


2020-12-28 13:00:19,844 [DEBUG] kashgari - predict output: (19, 102)
2020-12-28 13:00:19,846 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:00:19,851 [DEBUG] kashgari - predict seq_length: None, input: (2, 15, 102)


article: 49
None
1/1 [==============================] - 5s 5s/step


2020-12-28 13:00:25,073 [DEBUG] kashgari - predict output: (15, 102)
2020-12-28 13:00:25,075 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 2 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:00:25,082 [DEBUG] kashgari - predict seq_length: None, input: (2, 25, 102)


article: 50
None
1/1 [==============================] - 8s 8s/step


2020-12-28 13:00:33,554 [DEBUG] kashgari - predict output: (25, 102)
2020-12-28 13:00:33,557 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:00:33,561 [DEBUG] kashgari - predict seq_length: None, input: (2, 21, 102)


article: 51
None
1/1 [==============================] - 7s 7s/step


2020-12-28 13:00:40,834 [DEBUG] kashgari - predict output: (21, 102)
2020-12-28 13:00:40,836 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:00:40,840 [DEBUG] kashgari - predict seq_length: None, input: (2, 8, 102)


article: 52
None
1/1 [==============================] - 3s 3s/step


2020-12-28 13:00:43,739 [DEBUG] kashgari - predict output: (8, 102)
2020-12-28 13:00:43,745 [DEBUG] kashgari - predict output argmax: [[ 0  1  1  1  3  2  2  2  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1 10  5  5  1  1  1  1  1  1  1  1  1 10  5  5  1  1  1  1
   1  1  1  1  1  0]
 [ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  0]
 [ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 10  5  5  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1

article: 53
None
1/1 [==============================] - 9s 9s/step


2020-12-28 13:00:52,372 [DEBUG] kashgari - predict output: (25, 102)
2020-12-28 13:00:52,373 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 0 0 ... 0 0 0]]
2020-12-28 13:00:52,379 [DEBUG] kashgari - predict seq_length: None, input: (2, 16, 102)


article: 54
None
1/1 [==============================] - 5s 5s/step


2020-12-28 13:00:57,899 [DEBUG] kashgari - predict output: (16, 102)
2020-12-28 13:00:57,901 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:00:57,906 [DEBUG] kashgari - predict seq_length: None, input: (2, 15, 102)


article: 55
None
1/1 [==============================] - 5s 5s/step


2020-12-28 13:01:03,066 [DEBUG] kashgari - predict output: (15, 102)
2020-12-28 13:01:03,069 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:01:03,073 [DEBUG] kashgari - predict seq_length: None, input: (2, 15, 102)


article: 56
None
1/1 [==============================] - 5s 5s/step


2020-12-28 13:01:08,306 [DEBUG] kashgari - predict output: (15, 102)
2020-12-28 13:01:08,310 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:01:08,314 [DEBUG] kashgari - predict seq_length: None, input: (2, 9, 102)


article: 57
None
1/1 [==============================] - 3s 3s/step


2020-12-28 13:01:11,550 [DEBUG] kashgari - predict output: (9, 102)
2020-12-28 13:01:11,556 [DEBUG] kashgari - predict output argmax: [[ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  0]
 [ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  7  4  1  1  1  1  1  7  4  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  7  4  1  0]
 [ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1

article: 58
None
1/1 [==============================] - 7s 7s/step


2020-12-28 13:01:18,242 [DEBUG] kashgari - predict output: (19, 102)
2020-12-28 13:01:18,245 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 3 ... 1 1 1]]
2020-12-28 13:01:18,248 [DEBUG] kashgari - predict seq_length: None, input: (2, 15, 102)


article: 59
None
1/1 [==============================] - 5s 5s/step


2020-12-28 13:01:23,549 [DEBUG] kashgari - predict output: (15, 102)
2020-12-28 13:01:23,552 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:01:23,558 [DEBUG] kashgari - predict seq_length: None, input: (2, 23, 102)


article: 60
None
1/1 [==============================] - 8s 8s/step


2020-12-28 13:01:31,548 [DEBUG] kashgari - predict output: (23, 102)
2020-12-28 13:01:31,551 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 3 2 ... 1 1 1]]
2020-12-28 13:01:31,557 [DEBUG] kashgari - predict seq_length: None, input: (2, 19, 102)


article: 61
None
1/1 [==============================] - 7s 7s/step


2020-12-28 13:01:38,250 [DEBUG] kashgari - predict output: (19, 102)
2020-12-28 13:01:38,252 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:01:38,257 [DEBUG] kashgari - predict seq_length: None, input: (2, 20, 102)


article: 62
None
1/1 [==============================] - 7s 7s/step


2020-12-28 13:01:45,259 [DEBUG] kashgari - predict output: (20, 102)
2020-12-28 13:01:45,260 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 7 4 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 4 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:01:45,267 [DEBUG] kashgari - predict seq_length: None, input: (2, 14, 102)


article: 63
None
1/1 [==============================] - 5s 5s/step


2020-12-28 13:01:50,280 [DEBUG] kashgari - predict output: (14, 102)
2020-12-28 13:01:50,282 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:01:50,287 [DEBUG] kashgari - predict seq_length: None, input: (2, 11, 102)


article: 64
None
1/1 [==============================] - 4s 4s/step


2020-12-28 13:01:54,242 [DEBUG] kashgari - predict output: (11, 102)
2020-12-28 13:01:54,245 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:01:54,250 [DEBUG] kashgari - predict seq_length: None, input: (2, 24, 102)


article: 65
None
1/1 [==============================] - 8s 8s/step


2020-12-28 13:02:02,614 [DEBUG] kashgari - predict output: (24, 102)
2020-12-28 13:02:02,615 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 4 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:02:02,620 [DEBUG] kashgari - predict seq_length: None, input: (2, 11, 102)


article: 66
None
1/1 [==============================] - 4s 4s/step


2020-12-28 13:02:06,595 [DEBUG] kashgari - predict output: (11, 102)
2020-12-28 13:02:06,598 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:02:06,604 [DEBUG] kashgari - predict seq_length: None, input: (2, 37, 102)


article: 67
None
2/2 [==============================] - 13s 2s/step


2020-12-28 13:02:19,626 [DEBUG] kashgari - predict output: (37, 102)
2020-12-28 13:02:19,628 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:02:19,635 [DEBUG] kashgari - predict seq_length: None, input: (2, 23, 102)


article: 68
None
1/1 [==============================] - 8s 8s/step


2020-12-28 13:02:27,654 [DEBUG] kashgari - predict output: (23, 102)
2020-12-28 13:02:27,656 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:02:27,661 [DEBUG] kashgari - predict seq_length: None, input: (2, 11, 102)


article: 69
None
1/1 [==============================] - 4s 4s/step


2020-12-28 13:02:31,660 [DEBUG] kashgari - predict output: (11, 102)
2020-12-28 13:02:31,662 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:02:31,667 [DEBUG] kashgari - predict seq_length: None, input: (2, 22, 102)


article: 70
None
1/1 [==============================] - 8s 8s/step


2020-12-28 13:02:39,282 [DEBUG] kashgari - predict output: (22, 102)
2020-12-28 13:02:39,285 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 3 2 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:02:39,289 [DEBUG] kashgari - predict seq_length: None, input: (2, 13, 102)


article: 71
None
1/1 [==============================] - 5s 5s/step


2020-12-28 13:02:43,925 [DEBUG] kashgari - predict output: (13, 102)
2020-12-28 13:02:43,927 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:02:43,933 [DEBUG] kashgari - predict seq_length: None, input: (2, 14, 102)


article: 72
None
1/1 [==============================] - 5s 5s/step


2020-12-28 13:02:48,950 [DEBUG] kashgari - predict output: (14, 102)
2020-12-28 13:02:48,953 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 2 2 0]
 [0 1 1 ... 3 2 0]
 [0 3 2 ... 1 1 1]]
2020-12-28 13:02:48,957 [DEBUG] kashgari - predict seq_length: None, input: (2, 20, 102)


article: 73
None
1/1 [==============================] - 7s 7s/step


2020-12-28 13:02:56,013 [DEBUG] kashgari - predict output: (20, 102)
2020-12-28 13:02:56,016 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:02:56,021 [DEBUG] kashgari - predict seq_length: None, input: (2, 11, 102)


article: 74
None
1/1 [==============================] - 4s 4s/step


2020-12-28 13:02:59,999 [DEBUG] kashgari - predict output: (11, 102)
2020-12-28 13:03:00,001 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:03:00,006 [DEBUG] kashgari - predict seq_length: None, input: (2, 17, 102)


article: 75
None
1/1 [==============================] - 6s 6s/step


2020-12-28 13:03:06,068 [DEBUG] kashgari - predict output: (17, 102)
2020-12-28 13:03:06,070 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:03:06,076 [DEBUG] kashgari - predict seq_length: None, input: (2, 37, 102)


article: 76
None
2/2 [==============================] - 13s 2s/step


2020-12-28 13:03:19,133 [DEBUG] kashgari - predict output: (37, 102)
2020-12-28 13:03:19,135 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:03:19,143 [DEBUG] kashgari - predict seq_length: None, input: (2, 24, 102)


article: 77
None
1/1 [==============================] - 8s 8s/step


2020-12-28 13:03:27,397 [DEBUG] kashgari - predict output: (24, 102)
2020-12-28 13:03:27,400 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:03:27,406 [DEBUG] kashgari - predict seq_length: None, input: (2, 7, 102)


article: 78
None
1/1 [==============================] - 3s 3s/step


2020-12-28 13:03:29,964 [DEBUG] kashgari - predict output: (7, 102)
2020-12-28 13:03:29,968 [DEBUG] kashgari - predict output argmax: [[0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 3 2 2 2 1 1
  1 1 3 2 2 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 3 2 1 1 1 1 3 2 2 2 1 1 1 1 1 3 2 2 2 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 9 6 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 

article: 79
None
1/1 [==============================] - 9s 9s/step


2020-12-28 13:03:39,170 [DEBUG] kashgari - predict output: (27, 102)
2020-12-28 13:03:39,173 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 3 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:03:39,180 [DEBUG] kashgari - predict seq_length: None, input: (2, 15, 102)


article: 80
None
1/1 [==============================] - 5s 5s/step


2020-12-28 13:03:44,374 [DEBUG] kashgari - predict output: (15, 102)
2020-12-28 13:03:44,375 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:03:44,381 [DEBUG] kashgari - predict seq_length: None, input: (2, 18, 102)


article: 81
None
1/1 [==============================] - 6s 6s/step


2020-12-28 13:03:50,570 [DEBUG] kashgari - predict output: (18, 102)
2020-12-28 13:03:50,572 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:03:50,576 [DEBUG] kashgari - predict seq_length: None, input: (2, 17, 102)


article: 82
None
1/1 [==============================] - 6s 6s/step


2020-12-28 13:03:56,419 [DEBUG] kashgari - predict output: (17, 102)
2020-12-28 13:03:56,422 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:03:56,428 [DEBUG] kashgari - predict seq_length: None, input: (2, 41, 102)


article: 83
None
2/2 [==============================] - 14s 3s/step


2020-12-28 13:04:10,330 [DEBUG] kashgari - predict output: (41, 102)
2020-12-28 13:04:10,331 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:04:10,339 [DEBUG] kashgari - predict seq_length: None, input: (2, 24, 102)


article: 84
None
1/1 [==============================] - 8s 8s/step


2020-12-28 13:04:18,517 [DEBUG] kashgari - predict output: (24, 102)
2020-12-28 13:04:18,518 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:04:18,523 [DEBUG] kashgari - predict seq_length: None, input: (2, 33, 102)


article: 85
None
2/2 [==============================] - 11s 443ms/step


2020-12-28 13:04:29,725 [DEBUG] kashgari - predict output: (33, 102)
2020-12-28 13:04:29,729 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:04:29,734 [DEBUG] kashgari - predict seq_length: None, input: (2, 7, 102)


article: 86
None
1/1 [==============================] - 2s 2s/step


2020-12-28 13:04:32,215 [DEBUG] kashgari - predict output: (7, 102)
2020-12-28 13:04:32,226 [DEBUG] kashgari - predict output argmax: [[ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  0]
 [ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  0]
 [ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1

article: 87
None
1/1 [==============================] - 3s 3s/step


2020-12-28 13:04:35,377 [DEBUG] kashgari - predict output: (9, 102)
2020-12-28 13:04:35,382 [DEBUG] kashgari - predict output argmax: [[0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 9 6 1 1 1 1 1 1 1 1 1 1 1 1 1 9 6 6 6 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 3 2 2 2 1 1 3 2 2 2 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 3 2 2 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 3 2 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 3 2 1 1 1 1 3 2 1 1 1 1 1 1 1 1 1 1 3 2 2 2 1 1 1
  1 1 3 2 2 2 1 1 1 1 3 2 2 2 2 1 1 1 1 1 1 3 2 2 2 1 1 1 1 3 2 2 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 

article: 88
None
1/1 [==============================] - 7s 7s/step


2020-12-28 13:04:42,661 [DEBUG] kashgari - predict output: (21, 102)
2020-12-28 13:04:42,662 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:04:42,667 [DEBUG] kashgari - predict seq_length: None, input: (2, 12, 102)


article: 89
None
1/1 [==============================] - 4s 4s/step


2020-12-28 13:04:46,839 [DEBUG] kashgari - predict output: (12, 102)
2020-12-28 13:04:46,842 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:04:46,845 [DEBUG] kashgari - predict seq_length: None, input: (2, 16, 102)


article: 90
None
1/1 [==============================] - 5s 5s/step


2020-12-28 13:04:52,281 [DEBUG] kashgari - predict output: (16, 102)
2020-12-28 13:04:52,283 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 3 2 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:04:52,287 [DEBUG] kashgari - predict seq_length: None, input: (2, 12, 102)


article: 91
None
1/1 [==============================] - 4s 4s/step


2020-12-28 13:04:56,433 [DEBUG] kashgari - predict output: (12, 102)
2020-12-28 13:04:56,436 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:04:56,441 [DEBUG] kashgari - predict seq_length: None, input: (2, 19, 102)


article: 92
None
1/1 [==============================] - 6s 6s/step


2020-12-28 13:05:02,929 [DEBUG] kashgari - predict output: (19, 102)
2020-12-28 13:05:02,931 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:05:02,936 [DEBUG] kashgari - predict seq_length: None, input: (2, 9, 102)


article: 93
None
1/1 [==============================] - 3s 3s/step


2020-12-28 13:05:06,107 [DEBUG] kashgari - predict output: (9, 102)
2020-12-28 13:05:06,112 [DEBUG] kashgari - predict output argmax: [[ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  0]
 [ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  0]
 [ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1

article: 94
None
1/1 [==============================] - 8s 8s/step


2020-12-28 13:05:14,493 [DEBUG] kashgari - predict output: (25, 102)
2020-12-28 13:05:14,494 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:05:14,502 [DEBUG] kashgari - predict seq_length: None, input: (2, 19, 102)


article: 95
None
1/1 [==============================] - 6s 6s/step


2020-12-28 13:05:21,001 [DEBUG] kashgari - predict output: (19, 102)
2020-12-28 13:05:21,003 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:05:21,009 [DEBUG] kashgari - predict seq_length: None, input: (2, 24, 102)


article: 96
None
1/1 [==============================] - 8s 8s/step


2020-12-28 13:05:29,074 [DEBUG] kashgari - predict output: (24, 102)
2020-12-28 13:05:29,077 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:05:29,082 [DEBUG] kashgari - predict seq_length: None, input: (2, 27, 102)


article: 97
None
1/1 [==============================] - 9s 9s/step


2020-12-28 13:05:38,149 [DEBUG] kashgari - predict output: (27, 102)
2020-12-28 13:05:38,151 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 2 2 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:05:38,156 [DEBUG] kashgari - predict seq_length: None, input: (2, 12, 102)


article: 98
None
1/1 [==============================] - 4s 4s/step


2020-12-28 13:05:42,260 [DEBUG] kashgari - predict output: (12, 102)
2020-12-28 13:05:42,262 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:05:42,267 [DEBUG] kashgari - predict seq_length: None, input: (2, 20, 102)


article: 99
None
1/1 [==============================] - 7s 7s/step


2020-12-28 13:05:49,110 [DEBUG] kashgari - predict output: (20, 102)
2020-12-28 13:05:49,111 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:05:49,117 [DEBUG] kashgari - predict seq_length: None, input: (2, 23, 102)


article: 100
None
1/1 [==============================] - 8s 8s/step


2020-12-28 13:05:56,921 [DEBUG] kashgari - predict output: (23, 102)
2020-12-28 13:05:56,925 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:05:56,932 [DEBUG] kashgari - predict seq_length: None, input: (2, 6, 102)


article: 101
None
1/1 [==============================] - 2s 2s/step


2020-12-28 13:05:59,101 [DEBUG] kashgari - predict output: (6, 102)
2020-12-28 13:05:59,107 [DEBUG] kashgari - predict output argmax: [[0 1 1 1 1 1 1 1 1 3 2 2 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 3 2 2 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 

article: 102
None
1/1 [==============================] - 3s 3s/step


2020-12-28 13:06:02,576 [DEBUG] kashgari - predict output: (10, 102)
2020-12-28 13:06:02,577 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:06:02,581 [DEBUG] kashgari - predict seq_length: None, input: (2, 7, 102)


article: 103
None
1/1 [==============================] - 2s 2s/step


2020-12-28 13:06:05,081 [DEBUG] kashgari - predict output: (7, 102)
2020-12-28 13:06:05,088 [DEBUG] kashgari - predict output argmax: [[0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 3 2 2 2 1 1 1 1 1 1 1 1 3 2
  2 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 3 2 1 1 3 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 

article: 104
None
1/1 [==============================] - 2s 2s/step


2020-12-28 13:06:07,324 [DEBUG] kashgari - predict output: (6, 102)
2020-12-28 13:06:07,329 [DEBUG] kashgari - predict output argmax: [[0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 3 2 2 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 3 2 2 2
  2 2 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 9 6 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 

article: 105
None
1/1 [==============================] - 3s 3s/step


2020-12-28 13:06:10,819 [DEBUG] kashgari - predict output: (10, 102)
2020-12-28 13:06:10,821 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:06:10,825 [DEBUG] kashgari - predict seq_length: None, input: (2, 8, 102)


article: 106
None
1/1 [==============================] - 3s 3s/step


2020-12-28 13:06:13,623 [DEBUG] kashgari - predict output: (8, 102)
2020-12-28 13:06:13,627 [DEBUG] kashgari - predict output argmax: [[ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  0]
 [ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  3  2  2  2  2  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1 10  5  5  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  0]
 [ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1

article: 107
None
1/1 [==============================] - 10s 10s/step


2020-12-28 13:06:24,036 [DEBUG] kashgari - predict output: (31, 102)
2020-12-28 13:06:24,037 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 7 ... 2 2 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:06:24,043 [DEBUG] kashgari - predict seq_length: None, input: (2, 30, 102)


article: 108
None
1/1 [==============================] - 10s 10s/step


2020-12-28 13:06:34,120 [DEBUG] kashgari - predict output: (30, 102)
2020-12-28 13:06:34,121 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:06:34,129 [DEBUG] kashgari - predict seq_length: None, input: (2, 16, 102)


article: 109
None
1/1 [==============================] - 5s 5s/step


2020-12-28 13:06:39,614 [DEBUG] kashgari - predict output: (16, 102)
2020-12-28 13:06:39,617 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:06:39,622 [DEBUG] kashgari - predict seq_length: None, input: (2, 20, 102)


article: 110
None
1/1 [==============================] - 7s 7s/step


2020-12-28 13:06:46,362 [DEBUG] kashgari - predict output: (20, 102)
2020-12-28 13:06:46,363 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:06:46,372 [DEBUG] kashgari - predict seq_length: None, input: (2, 30, 102)


article: 111
None
1/1 [==============================] - 10s 10s/step


2020-12-28 13:06:56,462 [DEBUG] kashgari - predict output: (30, 102)
2020-12-28 13:06:56,464 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:06:56,469 [DEBUG] kashgari - predict seq_length: None, input: (2, 9, 102)


article: 112
None
1/1 [==============================] - 3s 3s/step


2020-12-28 13:06:59,639 [DEBUG] kashgari - predict output: (9, 102)
2020-12-28 13:06:59,643 [DEBUG] kashgari - predict output argmax: [[ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  0]
 [ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  0]
 [ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  9  6  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1

article: 113
None
1/1 [==============================] - 6s 6s/step


2020-12-28 13:07:06,052 [DEBUG] kashgari - predict output: (19, 102)
2020-12-28 13:07:06,054 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:07:06,060 [DEBUG] kashgari - predict seq_length: None, input: (2, 27, 102)


article: 114
None
1/1 [==============================] - 9s 9s/step


2020-12-28 13:07:15,185 [DEBUG] kashgari - predict output: (27, 102)
2020-12-28 13:07:15,188 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:07:15,194 [DEBUG] kashgari - predict seq_length: None, input: (2, 28, 102)


article: 115
None
1/1 [==============================] - 9s 9s/step


2020-12-28 13:07:24,617 [DEBUG] kashgari - predict output: (28, 102)
2020-12-28 13:07:24,619 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:07:24,624 [DEBUG] kashgari - predict seq_length: None, input: (2, 14, 102)


article: 116
None
1/1 [==============================] - 5s 5s/step


2020-12-28 13:07:29,435 [DEBUG] kashgari - predict output: (14, 102)
2020-12-28 13:07:29,437 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:07:29,442 [DEBUG] kashgari - predict seq_length: None, input: (2, 13, 102)


article: 117
None
1/1 [==============================] - 4s 4s/step


2020-12-28 13:07:33,885 [DEBUG] kashgari - predict output: (13, 102)
2020-12-28 13:07:33,887 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:07:33,894 [DEBUG] kashgari - predict seq_length: None, input: (2, 20, 102)


article: 118
None
1/1 [==============================] - 7s 7s/step


2020-12-28 13:07:40,664 [DEBUG] kashgari - predict output: (20, 102)
2020-12-28 13:07:40,667 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:07:40,670 [DEBUG] kashgari - predict seq_length: None, input: (2, 8, 102)


article: 119
None
1/1 [==============================] - 3s 3s/step


2020-12-28 13:07:43,470 [DEBUG] kashgari - predict output: (8, 102)
2020-12-28 13:07:43,474 [DEBUG] kashgari - predict output argmax: [[0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 3 2 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 3 1 1 3 2 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 

article: 120
None
2/2 [==============================] - 14s 3s/step


2020-12-28 13:07:57,306 [DEBUG] kashgari - predict output: (41, 102)
2020-12-28 13:07:57,308 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:07:57,313 [DEBUG] kashgari - predict seq_length: None, input: (2, 11, 102)


article: 121
None
1/1 [==============================] - 4s 4s/step


2020-12-28 13:08:01,127 [DEBUG] kashgari - predict output: (11, 102)
2020-12-28 13:08:01,128 [DEBUG] kashgari - predict output argmax: [[ 0  1  1 ...  1  1  0]
 [ 0  1  1 ...  1  1  0]
 [ 0  1  1 ...  1  1  0]
 ...
 [ 0  1  1 ...  1  1  0]
 [ 0  1  1 ...  4  4  0]
 [ 0  1 11 ...  1  1  1]]
2020-12-28 13:08:01,134 [DEBUG] kashgari - predict seq_length: None, input: (2, 19, 102)


article: 122
None
1/1 [==============================] - 6s 6s/step


2020-12-28 13:08:07,614 [DEBUG] kashgari - predict output: (19, 102)
2020-12-28 13:08:07,616 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:08:07,622 [DEBUG] kashgari - predict seq_length: None, input: (2, 13, 102)


article: 123
None
1/1 [==============================] - 4s 4s/step


2020-12-28 13:08:12,086 [DEBUG] kashgari - predict output: (13, 102)
2020-12-28 13:08:12,087 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:08:12,090 [DEBUG] kashgari - predict seq_length: None, input: (2, 6, 102)


article: 124
None
1/1 [==============================] - 2s 2s/step


2020-12-28 13:08:14,232 [DEBUG] kashgari - predict output: (6, 102)
2020-12-28 13:08:14,236 [DEBUG] kashgari - predict output argmax: [[ 0  1  1  1  1  3  2  2  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  0]
 [ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  3  2  1  1  1  1
   1  1  1  1  1  0]
 [ 0  1  1  1  1  1  1  1  1  1  1  1  3  2  2  1  1  1  1  1  1  1  1  1
   1  1  1  3  2  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  3  2

article: 125
None
1/1 [==============================] - 3s 3s/step


2020-12-28 13:08:17,724 [DEBUG] kashgari - predict output: (10, 102)
2020-12-28 13:08:17,726 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 0 1 1]]
2020-12-28 13:08:17,729 [DEBUG] kashgari - predict seq_length: None, input: (2, 8, 102)


article: 126
None
1/1 [==============================] - 3s 3s/step


2020-12-28 13:08:20,560 [DEBUG] kashgari - predict output: (8, 102)
2020-12-28 13:08:20,566 [DEBUG] kashgari - predict output argmax: [[0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 3 2 1 1 1 1 1 1 1 1 3 2 1 1 1 1 1 1 1 1 3
  2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 3 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 3 2 2 2 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 3 2 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 3 2 2 2 2 1 1 1 1 3 2 0]
 [0 1 1 1 1 1 1 1 1 1 

article: 127
None
1/1 [==============================] - 3s 3s/step


2020-12-28 13:08:23,375 [DEBUG] kashgari - predict output: (8, 102)
2020-12-28 13:08:23,380 [DEBUG] kashgari - predict output argmax: [[ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  0]
 [ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  9  6  6  6  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  0]
 [ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1

article: 128
None
1/1 [==============================] - 3s 3s/step


2020-12-28 13:08:26,874 [DEBUG] kashgari - predict output: (10, 102)
2020-12-28 13:08:26,876 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:08:26,882 [DEBUG] kashgari - predict seq_length: None, input: (2, 23, 102)


article: 129
None
1/1 [==============================] - 8s 8s/step


2020-12-28 13:08:34,669 [DEBUG] kashgari - predict output: (23, 102)
2020-12-28 13:08:34,671 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:08:34,676 [DEBUG] kashgari - predict seq_length: None, input: (2, 13, 102)


article: 130
None
1/1 [==============================] - 4s 4s/step


2020-12-28 13:08:39,165 [DEBUG] kashgari - predict output: (13, 102)
2020-12-28 13:08:39,167 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:08:39,171 [DEBUG] kashgari - predict seq_length: None, input: (2, 13, 102)


article: 131
None
1/1 [==============================] - 4s 4s/step


2020-12-28 13:08:43,659 [DEBUG] kashgari - predict output: (13, 102)
2020-12-28 13:08:43,662 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 3 2 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:08:43,666 [DEBUG] kashgari - predict seq_length: None, input: (2, 16, 102)


article: 132
None
1/1 [==============================] - 6s 6s/step


2020-12-28 13:08:49,225 [DEBUG] kashgari - predict output: (16, 102)
2020-12-28 13:08:49,228 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:08:49,232 [DEBUG] kashgari - predict seq_length: None, input: (2, 12, 102)


article: 133
None
1/1 [==============================] - 4s 4s/step


2020-12-28 13:08:53,450 [DEBUG] kashgari - predict output: (12, 102)
2020-12-28 13:08:53,452 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:08:53,454 [DEBUG] kashgari - predict seq_length: None, input: (2, 6, 102)


article: 134
None
1/1 [==============================] - 2s 2s/step


2020-12-28 13:08:55,660 [DEBUG] kashgari - predict output: (6, 102)
2020-12-28 13:08:55,664 [DEBUG] kashgari - predict output argmax: [[0 1 1 1 1 3 2 2 1 1 1 1 1 1 1 3 2 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 3 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 3 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 3 2 1 0]
 [0 1 1 1 1 1 1 1 1 1 

article: 135
None
1/1 [==============================] - 5s 5s/step


2020-12-28 13:09:00,956 [DEBUG] kashgari - predict output: (15, 102)
2020-12-28 13:09:00,958 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:09:00,963 [DEBUG] kashgari - predict seq_length: None, input: (2, 9, 102)


article: 136
None
1/1 [==============================] - 3s 3s/step


2020-12-28 13:09:04,158 [DEBUG] kashgari - predict output: (9, 102)
2020-12-28 13:09:04,162 [DEBUG] kashgari - predict output argmax: [[ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  3  2  2  2  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  0]
 [ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  0]
 [ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1

article: 137
None
1/1 [==============================] - 7s 7s/step


2020-12-28 13:09:11,433 [DEBUG] kashgari - predict output: (21, 102)
2020-12-28 13:09:11,434 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:09:11,441 [DEBUG] kashgari - predict seq_length: None, input: (2, 18, 102)


article: 138
None
1/1 [==============================] - 6s 6s/step


2020-12-28 13:09:17,637 [DEBUG] kashgari - predict output: (18, 102)
2020-12-28 13:09:17,639 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 2 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:09:17,645 [DEBUG] kashgari - predict seq_length: None, input: (2, 9, 102)


article: 139
None
1/1 [==============================] - 3s 3s/step


2020-12-28 13:09:20,783 [DEBUG] kashgari - predict output: (9, 102)
2020-12-28 13:09:20,788 [DEBUG] kashgari - predict output argmax: [[ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  0]
 [ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  0]
 [ 0  1  1  1  1  1  3  2  2  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1

article: 140
None
1/1 [==============================] - 7s 7s/step


2020-12-28 13:09:27,617 [DEBUG] kashgari - predict output: (20, 102)
2020-12-28 13:09:27,620 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:09:27,628 [DEBUG] kashgari - predict seq_length: None, input: (2, 25, 102)


article: 141
None
1/1 [==============================] - 9s 9s/step


2020-12-28 13:09:36,299 [DEBUG] kashgari - predict output: (25, 102)
2020-12-28 13:09:36,301 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 2 2 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:09:36,307 [DEBUG] kashgari - predict seq_length: None, input: (2, 29, 102)


article: 142
None
1/1 [==============================] - 10s 10s/step


2020-12-28 13:09:46,435 [DEBUG] kashgari - predict output: (29, 102)
2020-12-28 13:09:46,436 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:09:46,441 [DEBUG] kashgari - predict seq_length: None, input: (2, 9, 102)


article: 143
None
1/1 [==============================] - 3s 3s/step


2020-12-28 13:09:49,657 [DEBUG] kashgari - predict output: (9, 102)
2020-12-28 13:09:49,662 [DEBUG] kashgari - predict output argmax: [[ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  3  2  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  3  2  2  1  1  1
   1  1  1  1  1  0]
 [ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   3  2  1  1  1  0]
 [ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
   1  1  1

article: 144
None
1/1 [==============================] - 11s 11s/step


2020-12-28 13:10:00,977 [DEBUG] kashgari - predict output: (25, 102)
2020-12-28 13:10:00,980 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:10:00,986 [DEBUG] kashgari - predict seq_length: None, input: (2, 17, 102)


article: 145
None
1/1 [==============================] - 6s 6s/step


2020-12-28 13:10:07,010 [DEBUG] kashgari - predict output: (17, 102)
2020-12-28 13:10:07,012 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 3 0]
 [0 3 2 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:10:07,019 [DEBUG] kashgari - predict seq_length: None, input: (2, 17, 102)


article: 146
None
1/1 [==============================] - 6s 6s/step


2020-12-28 13:10:13,022 [DEBUG] kashgari - predict output: (17, 102)
2020-12-28 13:10:13,025 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:10:13,030 [DEBUG] kashgari - predict seq_length: None, input: (2, 19, 102)


article: 147
None
1/1 [==============================] - 7s 7s/step


2020-12-28 13:10:19,736 [DEBUG] kashgari - predict output: (19, 102)
2020-12-28 13:10:19,738 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 2 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:10:19,742 [DEBUG] kashgari - predict seq_length: None, input: (2, 12, 102)


article: 148
None
1/1 [==============================] - 4s 4s/step


2020-12-28 13:10:24,018 [DEBUG] kashgari - predict output: (12, 102)
2020-12-28 13:10:24,020 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:10:24,028 [DEBUG] kashgari - predict seq_length: None, input: (2, 24, 102)


article: 149
None
1/1 [==============================] - 8s 8s/step


2020-12-28 13:10:32,278 [DEBUG] kashgari - predict output: (24, 102)
2020-12-28 13:10:32,280 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:10:32,289 [DEBUG] kashgari - predict seq_length: None, input: (2, 76, 102)


article: 150
None
3/3 [==============================] - 26s 8s/step


2020-12-28 13:10:58,451 [DEBUG] kashgari - predict output: (76, 102)
2020-12-28 13:10:58,453 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:10:58,460 [DEBUG] kashgari - predict seq_length: None, input: (2, 18, 102)


article: 151
None
1/1 [==============================] - 6s 6s/step


2020-12-28 13:11:04,819 [DEBUG] kashgari - predict output: (18, 102)
2020-12-28 13:11:04,821 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:11:04,829 [DEBUG] kashgari - predict seq_length: None, input: (2, 41, 102)


article: 152
None
2/2 [==============================] - 14s 3s/step


2020-12-28 13:11:18,962 [DEBUG] kashgari - predict output: (41, 102)
2020-12-28 13:11:18,964 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:11:18,970 [DEBUG] kashgari - predict seq_length: None, input: (2, 28, 102)


article: 153
None
1/1 [==============================] - 10s 10s/step


2020-12-28 13:11:28,727 [DEBUG] kashgari - predict output: (28, 102)
2020-12-28 13:11:28,729 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:11:28,734 [DEBUG] kashgari - predict seq_length: None, input: (2, 22, 102)


article: 154
None
1/1 [==============================] - 8s 8s/step


2020-12-28 13:11:36,417 [DEBUG] kashgari - predict output: (22, 102)
2020-12-28 13:11:36,419 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:11:36,425 [DEBUG] kashgari - predict seq_length: None, input: (2, 27, 102)


article: 155
None
1/1 [==============================] - 9s 9s/step


2020-12-28 13:11:45,746 [DEBUG] kashgari - predict output: (27, 102)
2020-12-28 13:11:45,747 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 0 ... 1 1 1]]
2020-12-28 13:11:45,755 [DEBUG] kashgari - predict seq_length: None, input: (2, 34, 102)


article: 156
None
2/2 [==============================] - 12s 838ms/step


2020-12-28 13:11:57,687 [DEBUG] kashgari - predict output: (34, 102)
2020-12-28 13:11:57,690 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 0 0 ... 0 0 0]]
2020-12-28 13:11:57,697 [DEBUG] kashgari - predict seq_length: None, input: (2, 39, 102)


article: 157
None
2/2 [==============================] - 14s 2s/step


2020-12-28 13:12:11,285 [DEBUG] kashgari - predict output: (39, 102)
2020-12-28 13:12:11,286 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]
2020-12-28 13:12:11,293 [DEBUG] kashgari - predict seq_length: None, input: (2, 16, 102)


article: 158
None
1/1 [==============================] - 5s 5s/step


2020-12-28 13:12:16,826 [DEBUG] kashgari - predict output: (16, 102)
2020-12-28 13:12:16,828 [DEBUG] kashgari - predict output argmax: [[0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 ...
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 0]
 [0 1 1 ... 1 1 1]]


In [ ]:
labels

[[0, 113, 115, '今天', 'time'],
 [0, 227, 229, '麻豆', 'location'],
 [0, 237, 239, '麻豆', 'location'],
 [0, 295, 297, '今年', 'time'],
 [1, 31, 33, '今天', 'time'],
 [1, 40, 42, '昨天', 'time'],
 [1, 76, 80, '0.79', 'med_exam'],
 [1, 94, 96, '88', 'med_exam'],
 [1, 122, 124, '60', 'med_exam'],
 [1, 182, 184, '19', 'med_exam'],
 [1, 258, 261, '2.6', 'med_exam'],
 [1, 360, 363, '黃醫師', 'name'],
 [1, 366, 369, '6.6', 'med_exam'],
 [1, 385, 388, '6.6', 'med_exam'],
 [1, 394, 397, '8.3', 'med_exam'],
 [1, 407, 410, '8.3', 'med_exam'],
 [1, 414, 418, '四個月前', 'time'],
 [1, 418, 421, '8.3', 'med_exam'],
 [1, 463, 466, '6.2', 'med_exam'],
 [1, 469, 472, '三個月', 'time'],
 [1, 497, 500, '劉老師', 'name'],
 [1, 626, 629, '黃醫師', 'name'],
 [1, 742, 744, '中午', 'time'],
 [1, 867, 869, '21', 'time'],
 [1, 873, 875, '21', 'time'],
 [1, 881, 884, '12天', 'time'],
 [1, 890, 893, '12天', 'time'],
 [1, 902, 906, '三個星期', 'time'],
 [2, 170, 174, '1100', 'med_exam'],
 [2, 245, 249, '1145', 'med_exam'],
 [2, 275, 278, '500', 'me

In [ ]:
import csv
with open('BiLSTM_CRF_Model_2.tsv', 'w', newline='') as tsvfile:
  writer = csv.writer(tsvfile)
  writer.writerow(['article_id','start_position','end_position','entity_text','entity_type'])
  # 寫入二維表格
  writer.writerows(labels)